### Create Common User

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Daniel Martins",
  "email": "da@email.com",
  "password": "123456"
}

### Create Partner User

POST http://localhost:3000/partner/users
Content-Type: application/json

{
  "name": "Daniel Martins",
  "email": "d@email.com",
  "password": "123456"
}

### Create Partner User

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "d@email.com",
  "password": "123456"
}

### Create a Partner User

POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwibmFtZSI6IkRhbmllbCBNYXJ0aW5zIiwiZW1haWwiOiJkQGVtYWlsLmNvbSIsInJvbGVzIjpbIlBhcnRuZXIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0xNFQyMTozMzoyNy42OThaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xNFQyMTozMzoyNy42OThaIiwiaWF0IjoxNzE4NDYxODI5LCJleHAiOjE3MTg1NDgyMjl9.JtRaa4q1H0xA7pHAHl41f3OWv4-adUbTwMZvKqRWaPs

{
  "name": "FC"
}

### Create an event

POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwibmFtZSI6IkRhbmllbCBNYXJ0aW5zIiwiZW1haWwiOiJkQGVtYWlsLmNvbSIsInJvbGVzIjpbIlBhcnRuZXIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0xNFQyMTozMzoyNy42OThaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xNFQyMTozMzoyNy42OThaIiwiaWF0IjoxNzE4NDYxODI5LCJleHAiOjE3MTg1NDgyMjl9.JtRaa4q1H0xA7pHAHl41f3OWv4-adUbTwMZvKqRWaPs

{
  "name": "Evento 3",
  "description": "Festa junina",
  "date": "2024-06-12T23:21:34.60"
}

### lista todos os partners
GET http://localhost:3000/partners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6IkRhbmllbCBNYXJ0aW5zIiwiZW1haWwiOiJkYUBlbWFpbC5jb20iLCJyb2xlcyI6WyJVc2VyIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTRUMjE6MzM6MTcuNzgzWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTRUMjE6MzM6MTcuNzgzWiIsImlhdCI6MTcxODQxMDg3NSwiZXhwIjoxNzE4NDk3Mjc1fQ._AqtrkpwlsBuQE5SibnifvLKgq9D9WBjZRdvJrbPOgY
//TODO feito apenas para teste e listar os parceiros

### lista todos os eventos
GET http://localhost:3000/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwibmFtZSI6IkRhbmllbCBNYXJ0aW5zIiwiZW1haWwiOiJkQGVtYWlsLmNvbSIsInJvbGVzIjpbIlBhcnRuZXIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0xNFQyMTozMzoyNy42OThaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xNFQyMTozMzoyNy42OThaIiwiaWF0IjoxNzE4NDYxODI5LCJleHAiOjE3MTg1NDgyMjl9.JtRaa4q1H0xA7pHAHl41f3OWv4-adUbTwMZvKqRWaPs
//TODO feito apenas para teste e listar os parceiros